version: "3.9"

services:
  postgres:
    image: postgres:15 # Use the desired PostgreSQL version
    container_name: predictor_database
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "7235:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist data

  api:
    build:
      context: ../tournament-prediction-api
      dockerfile: Dockerfile
    container_name: predictor_api
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "8000:8000" # Adjust port mapping as needed
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local